apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    aadpodidbinding: openhack-pod-identity  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi-api
        image: registryjrc4068.azurecr.io/rudra/poi:v1 
        readinessProbe: 
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          successThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env :
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: azure-kvname-podid
              key: SQLPASSWORD
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: azure-kvname-podid
              key: SQLSERVER
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: azure-kvname-podid
              key: SQLUSER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: azure-kvname-podid
              key: SQLDBNAME
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-podid"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - port: 80
    targetPort: 80

