apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: rudra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi-api
        image: registryjrc4068.azurecr.io/rudra/poi:v1 
        readinessProbe: 
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          successThreshold: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env :
        - name: SQL_PASSWORD
          value: "kQ9pg2Kl9"
        - name: SQL_SERVER
          value: "sqlserverjrc4068"
        - name: SQL_USER
          value: "sqladminjRc4068"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: poiservice
  namespace: rudra
spec:
  selector:
    app: poi
  ports:
  - port: 80
    targetPort: 80

