# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                 # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: openhack-vault-cni       # Set to the name of your key vault
    cloudName: ""                          # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLSERVER
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLDBNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectType: secret
          objectVersion: ""
    tenantId: a038cd8f-3946-4703-ba91-4996cbb34b76                # The tenant ID of the key vault